### ISSUE TITLE
error: Missing optional dependency 'fsspec'.  Use pip or conda to install fsspec.

### ISSUE THREAD

**Issue by wickyhu** [ryjfgjl/ExcelToDatabase#2]
Hello,

I just downloaded and tried version 5.1 on one excel file, then I got below error:

Failed Excel: xxxxxx.xlsx, error: Missing optional dependency 'fsspec'.  Use pip or conda to install fsspec.

My OS is win11 without python installed.

Could you tell me how to resolve the issue?

Best Regards
Wicky Hu

**Comment by ryjfgjl** [comment]
I guess that the win11 is the reason to cause this error. 
I try to fix it. but I can not test.
I want to send a fixed exe program to you.
Could you give me a email here?

ryjfgjl

**Comment by wickyhu** [comment]
As tested, the issue was fixed in 5.2 beta.  
Thanks
Wicky
